name: jonnor-test
favicon: null
layout_spectrum: 0.40720021608285606
typography_spectrum: 0.8675086011644453
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#73603D'
    - '#BF8A49'
    - '#F2CA80'
    - '#5E5A59'
    - '#0D0D0D'
  brandStrength: 0.2800778003875166
  lightness: 0.9922386687248945
  saturation: 0.04302531643770635
  rhythmicContrast: 0.8248960317578167
purpose: []
