name: jonnor-test
favicon: null
layout_spectrum: 0.6390253650024533
typography_spectrum: 0.7027863431721926
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#468966'
    - '#FFF0A5'
    - '#FFB03B'
    - '#B64926'
    - '#8E2800'
  brandStrength: 0.19188234489411116
  lightness: 0.7766318789217621
  saturation: 0.6301512431818992
  rhythmicContrast: 0.6777367372997105
purpose: []
