name: jonnor-test
favicon: null
layout_spectrum: 0.572622784646228
typography_spectrum: 0.2757141792681068
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8384730003308505
  lightness: 0.8610998617950827
  saturation: 0.14117563632316887
  rhythmicContrast: 0.8030840773135424
purpose: []
